# Generated by Django 6.0.7 on 2026-08-01 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(db_index=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('accident', 'Accident'), ('embouteillage', 'Embouteillage'), ('inondation', 'Route inondée'), ('travaux', 'Travaux en cours'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('priorite', models.CharField(choices=[('elevee', 'Élevée'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('en_attente', 'En attente')], default='nouveau', max_length=10)),
                ('nb_confirmations', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mobility.roadsegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'statut'], name='reports_rep_type_fa77cc_idx'), models.Index(fields=['zone'], name='reports_rep_zone_31d1b7_idx')],
            },
        ),
    ]
