# Generated by Django 6.0.7 on 2026-08-01 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone', models.CharField(db_index=True, max_length=100)),
                ('zone_inondable', models.BooleanField(default=False)),
                ('source_geometrie', models.CharField(choices=[('osm', 'OpenStreetMap'), ('manuel', 'Manuel')], default='manuel', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_min', models.IntegerField(default=15)),
                ('score_predit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('facteurs', models.JSONField(default=dict)),
                ('version_modele', models.CharField(default='v1', max_length=20)),
                ('timestamp_prediction', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='mobility.roadsegment')),
            ],
            options={
                'ordering': ['-timestamp_prediction'],
            },
        ),
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('niveau_congestion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source', models.CharField(choices=[('simule', 'Simulé'), ('signalement', 'Signalement')], default='simule', max_length=20)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_records', to='mobility.roadsegment')),
            ],
            options={
                'indexes': [models.Index(fields=['segment', 'timestamp'], name='mobility_tr_segment_3acb81_idx')],
            },
        ),
    ]
