# Generated by Django 6.0.7 on 2026-08-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('pluie_moderee', 'Pluie modérée'), ('pluie_forte', 'Pluie forte')], default='normal', max_length=20)),
                ('condition', models.CharField(choices=[('ensoleille', 'Ensoleillé'), ('nuageux', 'Nuageux'), ('pluvieux', 'Pluvieux'), ('orageux', 'Orageux')], default='ensoleille', max_length=20)),
                ('temperature', models.FloatField(default=27.0)),
                ('intensite', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('historique_reel', 'Historique réel'), ('manuel', 'Manuel')], default='manuel', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
