# Generated by Django 6.0.7 on 2026-08-01 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alerte', 'Alerte'), ('signalement', 'Signalement'), ('systeme', 'Système')], max_length=15)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('lu', models.BooleanField(default=False)),
                ('lien_objet', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'lu'], name='notificatio_user_id_cf0127_idx')],
            },
        ),
    ]
