# Generated by Django 6.0.7 on 2026-08-01 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('type_donnees', models.CharField(choices=[('signalements', 'Signalements'), ('utilisateurs', 'Utilisateurs'), ('alertes', 'Alertes'), ('statistiques', 'Statistiques')], max_length=20)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('filtres', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=5)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('echec', 'Échec')], default='en_cours', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
