# Generated by Django 6.0.7 on 2026-08-01 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_predefini', models.BooleanField(default=False)),
                ('origine_label', models.CharField(max_length=150)),
                ('origine_lat', models.FloatField()),
                ('origine_lng', models.FloatField()),
                ('destination_label', models.CharField(max_length=150)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('type', models.CharField(choices=[('recommande', 'Itinéraire recommandé'), ('alternatif', 'Itinéraire alternatif'), ('autre', 'Autre itinéraire')], default='recommande', max_length=15)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duree_min', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraireSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conseil.itineraire')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.roadsegment')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('itineraire', 'ordre')},
            },
        ),
        migrations.AddField(
            model_name='itineraire',
            name='segments',
            field=models.ManyToManyField(related_name='itineraires', through='conseil.ItineraireSegment', to='mobility.roadsegment'),
        ),
    ]
